NAME = ft_display_file

CC = cc
CFLAGS = -Wall -Wextra -Werror

SRCS = main.c

# Regla all para compilar la binario
all: $(NAME)

# Crear el binario compilando el main.c
$(NAME): $(SRCS)
	$(CC) $(CFLAGS) -o $(NAME) $(SRCS)