NAME = libft.a

CC = cc
CFLAGS = -Wall -Wextra -Werror

SRCS = ft_putchar.c ft_swap.c ft_putstr.c ft_strlen.c ft_strcmp.c
OBJS = $(SRCS:.c=.o)

# Regla all para compilar la biblioteca
all: $(NAME)

# Crear la biblioteca estática libft.a
$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

# Compilar cada archivo fuente en un archivo objeto
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Limpiar los archivos objeto si ya no son necesarios
.PHONY: clean
clean:
	rm -rf $(OBJS)

# Regla para limpiar todo lo compilado, incluyendo la biblioteca
.PHONY: fclean
fclean: clean
	rm -rf $(NAME)

# Regla para recompilar todo
.PHONY: re
re: fclean all
